---
- hosts: all
  tasks:
  # First we reboot
  - name: Reboot boxes
    reboot:
    become: yes
  # Wipe Consul + nomad data
  - name: Wipe Consul server data
    file:
      path: /home/vagrant/consul_server/data
      state: absent
      force: yes
    become: yes
  - name: Wipe Consul client data
    file:
      path: /home/vagrant/consul_client/data
      state: absent
      force: yes
    become: yes
  - name: Wipe Nomad server data
    file:
      path: /home/vagrant/nomad_server/data
      state: absent
      force: yes
    become: yes
  - name: Wipe Nomad client data
    file:
      path: /home/vagrant/nomad_client/data
      state: absent
      force: yes
    become: yes
